### ISSUE TITLE
[데이터 시각화] 판매 현황 데이터 차트

### ISSUE THREAD

**Issue by heegu0311** [heegu0311/Partof_server#14]
### ISSUE

- Group: `server`
- Type:
1. [x] `feature`

### TODO

1. [ ] MongoDB & Mongoose 셋업
2. [ ] Loyverse API 데이터 > MongoDB 저장
3. [ ] sales 로직(라우트 / 컨트롤러) 추가
